### ISSUE TITLE
Impossible de modifier, supprimer ou copier une réservation, suite MàJ.

### ISSUE THREAD

**Issue by Rominet13** [mtalmont/grr#1]
Bonjour.

Tout d'abord merci pour le développement de GRR et son partage ! Notre club l'utilise depuis 8 ans, presque 9 maintenant. Et le design de la 2.5 est cool, encore plus pour la 3.7.
Notre page de réservation est la suivante : https://www.cnt-cnc.fr/reservation/week_all.php

J'ai quelques soucis depuis que j'ai fait la mise à jour vers la 2.5. Je n'arrivais pas à modifier, ou supprimer une réservation (faites par moi même ou pas, en admin ou pas). Je pensais que faire la mise à jour vers la 3.7 résoudrait le problème mais rien n'a changé. Soit c'est un bug qui vient de la première mise à jour et/ou de la base de données (que j'ai repris à mon prédécesseur) ou du navigateur (Firefox dernière version), ou alors du code php... Bref je ne sais pas, mais j'aimerai bien que l'admin puisse supprimer n'importe quelles réservations, ainsi que les auteurs puissent le faire avec leur propres réservations.
Voici les messages d'erreurs que j'obtiens :

**_Pour une modification de ma propre réservation (en tant qu'admin en plus, idem si utilisateur) :_**
--------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/14929379/30787176-1bbd3dcc-a151-11e7-9620-6a0b16a94d24.png)
**_Pour une suppression :_** 
![image](https://user-images.githubusercontent.com/14929379/30787189-5d384e22-a151-11e7-83cc-ca6beb602fe4.png)

En espérant que vous pourrez résoudre ce problème,
merci pour l'attention,
Rominet13.

**Comment by Rominet13** [comment]
Mince je me suis trompé de dépôt je pense...

**Comment by cyrzero** [comment]
Je ne suis jamais tombé sur ce genre d'erreur.
Quelle est votre version de PHP ? avez-vous les droits suffisant pour supprimer sur la base SQL ?
Vous pourriez essayer de faire une installation propre afin de voir si déja votre environement est compatible avec GRR et ensuite intégré votre base déja existante.

**Comment by Rominet13** [comment]
Oui, en effet, ca vient de ma version de PHP, la dernière en date 7.1.8. 
Je viens de faire le test, et avec la 5.6 pas de problème. J'avais oublié de tester cela, je m'étais contenter de voir que le site s'afficher bien. Je vais voir si le même problème a lieu avec la 7.0.
Merci beaucoup!

**Comment by Rominet13** [comment]
Avec PHP 7.0.22, je n'ai pas ce problème, mais c'est possible qu'il y ait d'autres erreurs vu que je n'ai pas tout testé. Y a-t-il une version de PHP conseillée ?
Et merci beaucoup pour votre réponse rapide!

**Comment by cyrzero** [comment]
Yes, nous avons testé qu'avec la version 7.0.x, il nous reste encore des fonctions à re-travailler pour améliorer la compatibilité avec les versions suivantes.

**Comment by Rominet13** [comment]
Ok super, merci beaucoup le coup de main!
